---
id: processing-with-go
base_name: smartlogic
tags: []
presentation_date: 2014-02-12
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :markdown
  name: Eric Oestrich
  email: eric@oestrich.org
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
